export const TEMPLATE_REGISTRY = {
  // Original set
  'editorial-elegant': { slug: 'editorial-elegant', name: 'Editorial Elegant', component: 'EditorialElegant' },
  'bold-showcase': { slug: 'bold-showcase', name: 'Bold Showcase', component: 'BoldShowcase' },
  'minimal-centered': { slug: 'minimal-centered', name: 'Minimal Centered', component: 'MinimalCentered' },
  'split-story': { slug: 'split-story', name: 'Split Story', component: 'SplitStory' },
  'cinematic-overlay': { slug: 'cinematic-overlay', name: 'Cinematic Overlay', component: 'CinematicOverlay' },
  'photo-only': { slug: 'photo-only', name: 'Photo Only', component: 'PhotoOnly' },
  'magazine-cover': { slug: 'magazine-cover', name: 'Magazine Cover', component: 'MagazineCover' },
  'minimal-frame': { slug: 'minimal-frame', name: 'Minimal Frame', component: 'MinimalFrame' },
  'polaroid-stack': { slug: 'polaroid-stack', name: 'Polaroid Stack', component: 'PolaroidStack' },
  'fullbleed-overlay': { slug: 'fullbleed-overlay', name: 'Fullbleed Overlay', component: 'FullbleedOverlay' },
  'split-portfolio': { slug: 'split-portfolio', name: 'Split Portfolio', component: 'SplitPortfolio' },
  'film-strip': { slug: 'film-strip', name: 'Film Strip', component: 'FilmStrip' },
  'testimonial-card': { slug: 'testimonial-card', name: 'Testimonial Card', component: 'TestimonialCard' },

  // New flexible templates (from explorer picks)
  'cinematic-fade': { slug: 'cinematic-fade', name: 'Cinematic Fade', component: 'CinematicFade' },
  'editorial-fullbleed': { slug: 'editorial-fullbleed', name: 'Editorial Full-Bleed', component: 'EditorialFullbleed' },
  'polaroid-realistic': { slug: 'polaroid-realistic', name: 'Polaroid Realistic', component: 'PolaroidRealistic' },
  'triptych-strip': { slug: 'triptych-strip', name: 'Triptych Strip', component: 'TriptychStrip' },
  'grid-2x2': { slug: 'grid-2x2', name: 'Grid 2×2', component: 'Grid2x2' },
  'minimal-centered-shape': { slug: 'minimal-centered-shape', name: 'Minimal Shape', component: 'MinimalCenteredShape' },
  'circle-gold': { slug: 'circle-gold', name: 'Circle Gold', component: 'CircleGold' },
  'duotone-wash': { slug: 'duotone-wash', name: 'Duotone Wash', component: 'DuotoneWash' },
  'split-half': { slug: 'split-half', name: 'Split 50/50', component: 'SplitHalf' },
  'typographic-hero': { slug: 'typographic-hero', name: 'Typographic Hero', component: 'TypographicHero' },
  'scrapbook-realistic': { slug: 'scrapbook-realistic', name: 'Scrapbook', component: 'ScrapbookRealistic' },
  'newspaper': { slug: 'newspaper', name: 'Newspaper', component: 'Newspaper' },
  'risograph': { slug: 'risograph', name: 'Risograph', component: 'Risograph' },
  'luxury-gold': { slug: 'luxury-gold', name: 'Luxury Gold', component: 'LuxuryGold' },
  'quote-card': { slug: 'quote-card', name: 'Quote Card', component: 'QuoteCard' },
  'geometric-blocks': { slug: 'geometric-blocks', name: 'Geometric Blocks', component: 'GeometricBlocks' },
  'collage-offset': { slug: 'collage-offset', name: 'Collage Offset', component: 'CollageOffset' },
  'stacked-letterforms': { slug: 'stacked-letterforms', name: 'Stacked Letterforms', component: 'StackedLetterforms' },
  'oversized-italic': { slug: 'oversized-italic', name: 'Oversized Italic', component: 'OversizedItalic' },
  'sidebar-index': { slug: 'sidebar-index', name: 'Sidebar Index', component: 'SidebarIndex' },
  'baseball-card': { slug: 'baseball-card', name: 'Baseball Card', component: 'BaseballCard' },
  'wax-seal-invite': { slug: 'wax-seal-invite', name: 'Wax Seal Invite', component: 'WaxSealInvite' },
  'blueprint-grid': { slug: 'blueprint-grid', name: 'Blueprint Grid', component: 'BlueprintGrid' },
  'photobooth-strip': { slug: 'photobooth-strip', name: 'Photobooth Strip', component: 'PhotoboothStrip' },
  'art-deco-fan': { slug: 'art-deco-fan', name: 'Art Deco Fan', component: 'ArtDecoFan' },
  'boarding-pass': { slug: 'boarding-pass', name: 'Boarding Pass', component: 'BoardingPass' },
  'memphis-zine': { slug: 'memphis-zine', name: 'Memphis 80s Zine', component: 'MemphisZine' },
  'apple-note': { slug: 'apple-note', name: 'Apple Note', component: 'AppleNote' },
} as const;
